settings:
 config_version: 2.1
 prefix: '&7[&bFreeze&eGUI&7]&r '
 check_update_on_join: true

messages:
 no_permission: '&cYou don''t have permission to perform this command!'
 freeze_usage: '&cCorrect usage: /freeze (Player Name)'
 unfreeze_usage: '&cCorrect usage: /unfreeze (Player Name)'
 freezeall_usage: '&cCorrect usage: /freezeall'
 unfreezeall_usage: '&cCorrect usage: /unfreezeall'
 no_freeze_yourself: '&cYou can''t Freeze yourself!'
 no_freeze_player: '&cYou can''t Freeze this player!'
 no_unfreeze_player: '&cYou can''t Unfreeze this player!'
 no_freezeall: '&cThe server isn''t Freezed!'
 already_freeze: '&cThis player is already Freezed!'
 already_freezeall: '&cThe server is already Freezed!'
 no_freeze: '&cThis player isn''t Freezed!'
 freeze_message: '&cYou have freezed &e%player%!'
 unfreeze_message: '&cYou have unfreezed &e%player%!'
 player_not_found: '&cPlayer not found!'
 must_player: '&cYou must be a player to perform this command!'
 quit_message: '&e%player% &7e'' uscito mentre era in Freeze!'
 notifyfreeze_message: '&cYou are now &eFreezed!'
 notifyunfreeze_message: '&cYou are now &eUnFreezed!'
 freezeall: '&cAll Player are now Freezed!'
 unfreezeall: '&cAll Player are now unFreezed!'
 no_freezeall: '&cThere aren''t player to Freeze!'
 no_unfreezeall: '&cThere aren''t player to unFreeze!'
 freezeall_item_click: '&cAll server are Freezed'
 update_message: '&7A new version of &eFreezeGUI &7is available!'

commands:
 punish_command: 'tempban %player% 7d Hack'
 slog_command: 'tempban %player% 10d Hack'

freezegui:
 display_name: '&c&lYou are now Freezed'
 Items:
  1:
   material: CHEST
   damage: 0
   amount: 1
   name: '&c&lADMITTED CHEAT'
   slot: 2
   lore:
   - '&cIf you click here, your ban'
   - '&7will be reduced'
  2:
   material: BOOK
   damage: 0
   amount: 1
   name: '&c&lJOIN TS'
   slot: 4
   lore:
   - '&cYou are now Freezed'
   - '&7Join in Ts'
   - ''
   - '&a&lts.example.com'
   - '&c&lSLOG=BAN'
  3:
   material: BOOK
   damage: 0
   amount: 1
   name: '&c&lJOIN TS'
   slot: 6
   lore:
   - '&cYou are now Freezed'
   - '&7Join in Ts'
   - ''
   - '&a&lts.example.com'
   - '&c&lSLOG=BAN'

suregui:
 display_name: '&c&lConfirm?'
 Items:
  1:
   material: WOOL
   damage: 13
   amount: 1
   name: '&c&lYes'
   slot: 2
   lore:
   - '&cConfirm that you are using Hack'
  2:
   material: WOOL
   damage: 14
   amount: 1
   name: '&c&lNo'
   slot: 6
   lore:
   - '&cGo back'

freezeallgui:
 display_name: '&c&lFreeze ALL!'
 Items:
  1:
   material: BOOK
   damage: 0
   amount: 1
   name: '&c&lFreeze ALL'
   slot: 4
   lore:
   - '&cAll Player are Freezed'