name: FreezeGUI
version: 1.8
author: Maymity
main: it.maymity.freezegui.Main
commands:
  freeze:
    description: With this command you can Freeze a player
  unfreeze:
    description: With this command you can unFreeze a player